### ISSUE TITLE
BUG: slice bounds out of range

### ISSUE THREAD

**Issue by yann-sjtu** [libp2p/go-yamux#65] opened 2021-10-09 02:46 UTC
it panics on windows 

https://github.com/libp2p/go-libp2p/issues/1108

```
panic: runtime error: slice bounds out of range [4203:726]

goroutine 3916 [running]:
internal/poll.(*FD).Write(0xc012d70c80, 0xc004cda800, 0x2d6, 0x400, 0x0, 0x0, 0x0)
        C:/Program Files/Go/src/internal/poll/fd_windows.go:645 +0x490
net.(*netFD).Write(0xc012d70c80, 0xc004cda800, 0x2d6, 0x400, 0x400, 0xc004cda800, 0x2d6)
        C:/Program Files/Go/src/net/fd_posix.go:73 +0x56
net.(*conn).Write(0xc004c119a8, 0xc004cda800, 0x2d6, 0x400, 0x0, 0x0, 0x0)
        C:/Program Files/Go/src/net/net.go:194 +0x95
github.com/libp2p/go-libp2p-noise.(*secureSession).writeMsgInsecure(...)
        D:/goWork/pkg/mod/github.com/libp2p/go-libp2p-noise@v0.2.2/rw.go:155
github.com/libp2p/go-libp2p-noise.(*secureSession).Write(0xc0033438c0, 0xc0077da000, 0x2c4, 0x400, 0x0, 0x0, 0x0)
        D:/goWork/pkg/mod/github.com/libp2p/go-libp2p-noise@v0.2.2/rw.go:123 +0x288
github.com/libp2p/go-yamux/v2.(*Session).sendLoop(0xc0131fdc20, 0x0, 0x0)
        D:/goWork/pkg/mod/github.com/libp2p/go-yamux/v2@v2.2.0/session.go:548 +0x2b5
github.com/libp2p/go-yamux/v2.(*Session).send(0xc0131fdc20)
        D:/goWork/pkg/mod/github.com/libp2p/go-yamux/v2@v2.2.0/session.go:452 +0x32
created by github.com/libp2p/go-yamux/v2.newSession
        D:/goWork/pkg/mod/github.com/libp2p/go-yamux/v2@v2.2.0/session.go:133 +0x41d
```

**Comment by Stebalien** [comment] 2021-10-10 23:29
1. Please try running your program with the race detector enabled.
2. Are you using https://github.com/libp2p/go-buffer-pool anywhere in your program?

This looks like memory corruption, which could be caused by anything.

**Comment by MarcoPolo** [comment] 2022-06-24 16:20
A bit more context, this is most likely a bug in Go itself since in that function that @Stebalien linked we simply pass in a buf and it's the function itself that does the out of bounds indexing.

**Comment by BigLep** [comment] 2022-07-01 16:25
2022-07-01 conversation: we're also missing a repo case here.  @marten-seemann tried in a windows VM over a couple days.  

We're going to close this because we haven't been able to repro.  Please feel free to reopen if it happens again.

**Closed by BigLep** 2022-07-01 16:25 UTC
