### ISSUE TITLE
Stall under high load

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-yamux#61] opened 2021-07-26 15:47 UTC
It appears that transfer can stall under high load. Reproducer is https://github.com/raulk/whitenoise/tree/repro/lotus-6602.

This appears to have been introduced in the recent send window changes.

**Comment by aschmahmann** [comment] 2021-08-06 15:11
Update: 08-06-21: The above does not reproduce on @marten-seemann's machine. This is stalled until we get more information or the ability to reproduce. @raulk any assistance would be appreciated.

**Comment by BigLep** [comment] 2021-09-03 15:18
Context: this was biting Lotus.  Lotus worked around this by downgrading the version of yamux used.

**Comment by Stebalien** [comment] 2021-10-18 17:27
Update: I have a theory that this is caused by synchronous writes. The changes in question make the stream window ramp up over multiple round-trips instead of starting out at a full 16MiB (which is what go-libp2p-yamux configured the window to be in the past). Now that it ramps up slowly, attempting to write a megabyte may now _block_ waiting for the other side to read.

**Comment by BigLep** [comment] 2021-11-12 16:45
Closing since haven't been able to reproduce at the yamux layer and Lotus is now unpinned per https://github.com/filecoin-project/lotus/pull/7532

**Closed by BigLep** 2021-11-12 16:45 UTC
Labels: status/blocked
